-- DB-level UNIQUE backstop on `graphs.name`.
--
-- `GraphStore::create_from_yaml` enforces the CREATE-only collision
-- rule via a SELECT-then-INSERT inside a `sqlx::Transaction`. That is
-- correct for the operator-driven, single-caller case `jarvis apply`
-- runs in, but two concurrent applies racing the SELECT-then-INSERT
-- could in principle both insert. The fast-path SELECT stays as-is
-- (clean error semantics for the common case); this migration adds
-- the DB-level guarantee so the race is structurally impossible.
-- `create_from_yaml` catches the resulting Postgres SQLSTATE 23505 and
-- surfaces it as `GraphStoreError::GraphAlreadyExists`.
--
-- `ALTER TABLE ... ADD CONSTRAINT ... UNIQUE` rather than
-- `CREATE UNIQUE INDEX` matches the schema voice in `0001_initial.sql`,
-- which avoids ad-hoc indexes and declares uniqueness via inline
-- `UNIQUE (...)` clauses. The post-hoc form creates a backing index
-- implicitly and registers a named constraint that surfaces in
-- `\d graphs` as a UNIQUE CONSTRAINT.
--
-- No `IF NOT EXISTS`: a corrupted migration tracker should surface
-- loudly rather than be masked by idempotent DDL.

ALTER TABLE graphs ADD CONSTRAINT graphs_name_unique UNIQUE (name);
