//! Stage 5.4 (JAR2-81) — live integration test for the child → parent
//! signal path (first live exercise of
//! [`temporalio_sdk::WorkflowContext::external_workflow`] in production-
//! shaped code).
//!
//! Env-gated behind `TEMPORAL_LIVE_TEST=1`. Spawns two `AgentWorkflow`
//! instances against a real Temporal Server:
//!
//! 1. A **parent** workflow that loops idle, capturing every `Trigger`
//!    that lands in its `pending_triggers` bucket via a custom `Decide`
//!    impl.
//! 2. A **child** workflow with `parent_handle: Some(ParentRef { ... })`
//!    pointing at the parent. The child runs a scripted
//!    `EmitOutput → Retire` sequence; the `Decision::EmitOutput` arm of
//!    `AgentWorkflow::run` builds a `Trigger::ChildOutput` and fires it
//!    at the parent via `ctx.external_workflow(...).signal(...)`.
//!
//! ## Happy path assertions
//!
//! - Parent's `cumulative_triggers_observed >= 1` (the
//!   `Trigger::ChildOutput` signal landed on workflow state via the
//!   JAR2-59 `external_signal` handler).
//! - The captured trigger is a `Trigger::ChildOutput` carrying the
//!   right `child_ref.workflow_id` + `agent_name` + `output_id`.
//!
//! ## Failure-mode assertions
//!
//! - Child with `parent_handle.workflow_id` pointing at a non-existent
//!   workflow still completes normally (retires with `AgentResult::Retired`).
//!   Per Stage 5 Project decision 10: signal failures are logged + the
//!   child continues — the child's output is durable on its own FS
//!   regardless of whether the parent observed the signal.
//!
//! ## SDK divergence from the ticket pseudocode
//!
//! The JAR2-81 ticket sketched
//! `ctx.signal_external_workflow(workflow_id, signal_name, payload).await`.
//! The real `temporalio-sdk` v0.4.0 API is a two-step typed chain:
//! `ctx.external_workflow(workflow_id, run_id).signal(SignalDef, payload).await`
//! where `SignalDef` is the compile-time marker generated by the
//! `#[signal]` macro (here `AgentWorkflow::external_signal`). Documented
//! in `scratch/temporal_rust_sdk_smoke.md` § 2 row 8 / § 3.

use std::collections::VecDeque;
use std::env;
use std::sync::{Arc, Mutex, OnceLock};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use anyhow::{Context, Result};
use async_trait::async_trait;
use chrono::Utc;
use temporalio_client::{
    Client, ClientOptions, Connection, ConnectionOptions, WorkflowExecuteUpdateOptions,
    WorkflowGetResultOptions, WorkflowSignalOptions, WorkflowStartOptions,
};
use temporalio_common::telemetry::TelemetryOptions;
use temporalio_sdk_core::{CoreRuntime, RuntimeOptions, Url};
use uuid::Uuid;

use jarvis_node::agent_ref::{AgentId, GraphId};
use jarvis_node::decision::{ContextBundle, Decide, Decision};
use jarvis_node::evidence::EvidenceRecord;
use jarvis_node::fs::AgentFs;
use jarvis_node::mandate::Mandate;
use jarvis_node::storage::{AgentStorage, MemoryStorage};
use jarvis_node::tools::ToolRegistry;
use jarvis_node::trigger::Trigger;
use jarvis_temporal::activities::set_decision_script;
use jarvis_temporal::worker::{
    build_worker, install_agent_storage, install_decide, install_tool_registry,
};
use jarvis_temporal::workflow::{
    AgentInput, AgentResult, AgentSnapshot, AgentWorkflow, FsHandle, ParentRef,
};

const DEFAULT_ADDRESS: &str = "http://localhost:7233";
const DEFAULT_NAMESPACE: &str = "default";

/// Shared in-memory storage backend: parent + child both run their
/// `persist_output` / `persist_retirement` activities against this. The
/// test driver uses the same `Arc<MemoryStorage>` to plant the child's
/// evidence (so the scripted `EmitOutput` resolves provenance).
static SHARED_STORAGE: OnceLock<Arc<MemoryStorage>> = OnceLock::new();

/// One installed `Decide` for both workflows. The implementation routes
/// per-bundle by [`Mandate.text`] (cheapest discriminator) and records
/// every trigger the parent observes onto [`PARENT_OBSERVED_TRIGGERS`].
/// See [`RoutingDecide`] for the routing rules.
static PARENT_OBSERVED_TRIGGERS: OnceLock<Arc<Mutex<Vec<Trigger>>>> = OnceLock::new();

/// Static scripts the [`RoutingDecide`] consumes — one FIFO per role.
/// Set fresh by [`install_role_scripts`] at the top of each `run_*`
/// test body so the two live tests in this binary don't leak state
/// across each other.
static CHILD_SCRIPT: OnceLock<Mutex<VecDeque<Decision>>> = OnceLock::new();
static PARENT_SCRIPT: OnceLock<Mutex<VecDeque<Decision>>> = OnceLock::new();

const PARENT_MANDATE_TEXT: &str = "JAR2-81-parent";
const CHILD_MANDATE_TEXT: &str = "JAR2-81-child";

/// Serializes the two live tests in this binary so they don't share
/// `PARENT_OBSERVED_TRIGGERS` or the per-role scripts across a parallel
/// test run.
static LIVE_TEST_GUARD: Mutex<()> = Mutex::new(());

static INIT: std::sync::Once = std::sync::Once::new();

/// One-shot install of the shared storage + tool registry + `Decide`
/// impl. Subsequent calls are no-ops (the install hooks panic on
/// double-install; `Once` guards against that).
fn ensure_installed() -> Arc<MemoryStorage> {
    INIT.call_once(|| {
        let storage: Arc<MemoryStorage> = Arc::new(MemoryStorage::new());
        SHARED_STORAGE
            .set(Arc::clone(&storage))
            .expect("SHARED_STORAGE set exactly once");
        let dyn_storage: Arc<dyn AgentStorage> = storage;
        install_agent_storage(dyn_storage);

        // Empty registry — the JAR2-81 tests don't dispatch tools. The
        // execute_tool activity body asserts the registry is installed
        // even if no tool is registered, so we install an empty one.
        install_tool_registry(Arc::new(ToolRegistry::new()));

        PARENT_OBSERVED_TRIGGERS
            .set(Arc::new(Mutex::new(Vec::new())))
            .expect("PARENT_OBSERVED_TRIGGERS set exactly once");

        // Seed the per-role script slots with empty queues; tests
        // replace contents via `install_role_scripts`.
        CHILD_SCRIPT
            .set(Mutex::new(VecDeque::new()))
            .expect("CHILD_SCRIPT set exactly once");
        PARENT_SCRIPT
            .set(Mutex::new(VecDeque::new()))
            .expect("PARENT_SCRIPT set exactly once");

        install_decide(Arc::new(RoutingDecide));
    });
    SHARED_STORAGE.get().cloned().expect("storage installed")
}

/// `Decide` that routes per-tick by `bundle.mandate.text` and records
/// every trigger the parent observes. Scripts come from
/// [`PARENT_SCRIPT`] / [`CHILD_SCRIPT`]; the fallback when a script is
/// empty is `Decision::Idle { 50ms }` so a misconfigured test loops
/// politely rather than panicking the activity.
struct RoutingDecide;

#[async_trait]
impl Decide for RoutingDecide {
    async fn decide(&self, bundle: ContextBundle) -> anyhow::Result<Decision> {
        let script = match bundle.mandate.text.as_str() {
            PARENT_MANDATE_TEXT => {
                // Record every trigger the parent sees this tick. The
                // happy-path assertion at the end of `run_happy_path`
                // reads this vector.
                if !bundle.triggers.is_empty() {
                    let log = PARENT_OBSERVED_TRIGGERS
                        .get()
                        .expect("PARENT_OBSERVED_TRIGGERS installed")
                        .clone();
                    let mut guard = log.lock().expect("trigger log mutex poisoned");
                    for t in &bundle.triggers {
                        guard.push(t.clone());
                    }
                }
                PARENT_SCRIPT.get().expect("PARENT_SCRIPT installed")
            }
            CHILD_MANDATE_TEXT => CHILD_SCRIPT.get().expect("CHILD_SCRIPT installed"),
            other => panic!(
                "RoutingDecide saw unexpected mandate text: {other:?} \
                 (JAR2-81 tests script only PARENT_MANDATE_TEXT / CHILD_MANDATE_TEXT)"
            ),
        };
        let popped = script.lock().expect("script mutex poisoned").pop_front();
        Ok(popped.unwrap_or(Decision::Idle {
            next_after: Duration::from_millis(50),
        }))
    }
}

/// Replace the contents of the per-role script slots. Called at the
/// start of each live-test body so the two tests in this binary stay
/// isolated.
fn install_role_scripts(parent: Vec<Decision>, child: Vec<Decision>) {
    {
        let mut p = PARENT_SCRIPT
            .get()
            .expect("PARENT_SCRIPT installed")
            .lock()
            .expect("PARENT_SCRIPT mutex poisoned");
        *p = parent.into();
    }
    {
        let mut c = CHILD_SCRIPT
            .get()
            .expect("CHILD_SCRIPT installed")
            .lock()
            .expect("CHILD_SCRIPT mutex poisoned");
        *c = child.into();
    }
    // Belt-and-braces: clear the DECISION_SCRIPT static so neither
    // workflow pops a stale entry from a previous test binary's run.
    set_decision_script(Vec::new());
}

fn reset_parent_observed_triggers() {
    let log = PARENT_OBSERVED_TRIGGERS
        .get()
        .expect("PARENT_OBSERVED_TRIGGERS installed")
        .clone();
    let mut guard = log.lock().expect("trigger log mutex poisoned");
    guard.clear();
}

fn parent_observed_triggers_snapshot() -> Vec<Trigger> {
    let log = PARENT_OBSERVED_TRIGGERS
        .get()
        .expect("PARENT_OBSERVED_TRIGGERS installed")
        .clone();
    let guard = log.lock().expect("trigger log mutex poisoned");
    guard.clone()
}

fn run_suffix() -> String {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis().to_string())
        .unwrap_or_else(|_| "no-suffix".into())
}

async fn build_client() -> Result<Client> {
    let address = env::var("TEMPORAL_ADDRESS").unwrap_or_else(|_| DEFAULT_ADDRESS.into());
    let namespace = env::var("TEMPORAL_NAMESPACE").unwrap_or_else(|_| DEFAULT_NAMESPACE.into());
    let url = Url::parse(&address).context("parsing TEMPORAL_ADDRESS")?;
    let connection_options = ConnectionOptions::new(url).build();
    let connection = Connection::connect(connection_options)
        .await
        .context("connecting to Temporal Server (is `temporal server start-dev` running?)")?;
    let client_options = ClientOptions::new(namespace).build();
    let client = Client::new(connection, client_options).context("building Temporal client")?;
    Ok(client)
}

/// Happy-path live test — parent + child against the same task queue;
/// child emits one output, parent observes the resulting
/// `Trigger::ChildOutput` signal.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
#[allow(clippy::await_holding_lock)]
async fn child_emit_signals_parent_with_child_output_trigger() {
    if env::var("TEMPORAL_LIVE_TEST").ok().as_deref() != Some("1") {
        eprintln!(
            "skipping child_emit_signals_parent_with_child_output_trigger; \
             set TEMPORAL_LIVE_TEST=1 with a local Temporal Server to run"
        );
        return;
    }
    let _guard = LIVE_TEST_GUARD.lock().unwrap_or_else(|p| p.into_inner());
    run_happy_path().await.expect("JAR2-81 happy path");
}

/// Failure-mode live test — child's `parent_handle.workflow_id` points
/// at a non-existent workflow; the child's `signal_external_workflow`
/// call fails, but the child completes normally per Stage 5 Project
/// decision 10.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
#[allow(clippy::await_holding_lock)]
async fn child_continues_normally_when_parent_signal_fails() {
    if env::var("TEMPORAL_LIVE_TEST").ok().as_deref() != Some("1") {
        eprintln!(
            "skipping child_continues_normally_when_parent_signal_fails; \
             set TEMPORAL_LIVE_TEST=1 with a local Temporal Server to run"
        );
        return;
    }
    let _guard = LIVE_TEST_GUARD.lock().unwrap_or_else(|p| p.into_inner());
    run_failure_path().await.expect("JAR2-81 failure path");
}

async fn run_happy_path() -> Result<()> {
    let suffix = run_suffix();
    let task_queue = format!("jarvis-jar2-81-happy-{suffix}");
    let parent_prefix = format!("graphs/g-jar2-81/agents/parent-{suffix}");
    let child_prefix = format!("graphs/g-jar2-81/agents/child-{suffix}");
    let parent_workflow_id = format!("graphs/g-jar2-81/agents/parent-{suffix}");
    let child_workflow_id = format!("graphs/g-jar2-81/agents/child-{suffix}");

    let storage = ensure_installed();
    reset_parent_observed_triggers();

    // Plant one evidence record under the CHILD's FS prefix so the
    // scripted EmitOutput resolves provenance. EvidenceId is content-
    // addressed; we capture the returned id for the post-run assertion
    // on the trigger payload.
    let plant_mandate = Mandate::new("plant", Duration::from_millis(0), None);
    let plant_storage: Arc<dyn AgentStorage> = storage.clone();
    let plant_fs = AgentFs::new_with_storage(plant_storage, &child_prefix, &plant_mandate)
        .await
        .context("open planting AgentFs for child")?;
    let planted_id = plant_fs
        .record_evidence(EvidenceRecord::new(
            "echo",
            serde_json::json!({"k": "v"}),
            serde_json::json!({"hit": true}),
            Utc::now(),
        ))
        .await
        .context("plant evidence for child EmitOutput")?;

    // Parent script: idle forever — its tick loop wakes on every signal
    // arrival (the JAR2-60 wake gate races `wait_condition` against the
    // idle timer), so an empty script + Idle fallback is enough for the
    // ChildOutput signal to land and be drained into a `decide_next_action`
    // bundle that the `RoutingDecide` will record. A `retire` signal at
    // the end of the test ends the parent cleanly.
    let parent_script: Vec<Decision> = Vec::new();
    // Child script: EmitOutput citing the planted evidence, then Retire.
    let child_script = vec![
        Decision::EmitOutput {
            content: "JAR2-81 child output".into(),
            evidence: vec![planted_id.clone()],
        },
        Decision::Retire {
            reason: "JAR2-81 child: scripted retire".into(),
        },
    ];
    install_role_scripts(parent_script, child_script);

    let telemetry_options = TelemetryOptions::builder().build();
    let runtime = CoreRuntime::new_assume_tokio(
        RuntimeOptions::builder()
            .telemetry_options(telemetry_options)
            .build()
            .map_err(|e| anyhow::anyhow!("RuntimeOptions build failed: {e}"))?,
    )?;
    let client = build_client().await?;
    let mut worker = build_worker(&runtime, client.clone(), &task_queue)?;
    let shutdown = worker.shutdown_handle();

    let driver_task_queue = task_queue.clone();
    let driver_parent_prefix = parent_prefix.clone();
    let driver_child_prefix = child_prefix.clone();
    let driver_parent_workflow_id = parent_workflow_id.clone();
    let driver_child_workflow_id = child_workflow_id.clone();
    let driver_planted_id = planted_id.clone();
    let driver = tokio::spawn(async move {
        struct ShutdownGuard<F: Fn()>(F);
        impl<F: Fn()> Drop for ShutdownGuard<F> {
            fn drop(&mut self) {
                (self.0)();
            }
        }
        let _guard = ShutdownGuard(shutdown);
        drive_happy_path(
            client,
            &driver_task_queue,
            &driver_parent_workflow_id,
            &driver_child_workflow_id,
            &driver_parent_prefix,
            &driver_child_prefix,
            driver_planted_id,
        )
        .await
    });

    let worker_result = tokio::time::timeout(Duration::from_secs(90), worker.run())
        .await
        .map_err(|_| anyhow::anyhow!("worker.run() timed out (90s)"))?
        .map_err(|e| anyhow::anyhow!("worker.run() exited with error: {e}"));
    let driver_result = driver.await.context("driver task panicked")?;

    worker_result?;
    driver_result?;
    Ok(())
}

async fn drive_happy_path(
    client: Client,
    task_queue: &str,
    parent_workflow_id: &str,
    child_workflow_id: &str,
    parent_prefix: &str,
    child_prefix: &str,
    planted_id: jarvis_node::evidence::EvidenceId,
) -> Result<()> {
    // Start the parent first so it's running and addressable when the
    // child fires the signal.
    let parent_input = AgentInput {
        cfg: Default::default(),
        fs_handle: FsHandle {
            prefix: parent_prefix.into(),
        },
        parent_handle: None,
        carryover: None,
        mandate: Mandate::new(PARENT_MANDATE_TEXT, Duration::from_millis(50), None),
        graph_id: GraphId::new(Uuid::nil()),
        agent_id: AgentId::new(Uuid::nil()),
        agent_name: "parent".into(),
    };
    let parent_handle = client
        .start_workflow(
            AgentWorkflow::run,
            parent_input,
            WorkflowStartOptions::new(task_queue, parent_workflow_id).build(),
        )
        .await
        .context("start_workflow(parent)")?;
    eprintln!("JAR2-81 happy: parent started at {parent_workflow_id}");

    // Distinct UUID for the child's structural agent_id (recorded onto
    // the `Trigger::ChildOutput.child_ref.agent_id` so the post-run
    // assertion can pin it).
    let child_agent_uuid =
        Uuid::parse_str("11111111-2222-3333-4444-555555555555").expect("hand-picked uuid is valid");
    let child_agent_id = AgentId::new(child_agent_uuid);
    let child_input = AgentInput {
        cfg: Default::default(),
        fs_handle: FsHandle {
            prefix: child_prefix.into(),
        },
        parent_handle: Some(ParentRef {
            workflow_id: parent_workflow_id.to_string(),
            ..ParentRef::default()
        }),
        carryover: None,
        mandate: Mandate::new(CHILD_MANDATE_TEXT, Duration::from_millis(50), None),
        graph_id: GraphId::new(Uuid::nil()),
        agent_id: child_agent_id,
        agent_name: "fda_scraper".into(),
    };
    let child_handle = client
        .start_workflow(
            AgentWorkflow::run,
            child_input,
            WorkflowStartOptions::new(task_queue, child_workflow_id).build(),
        )
        .await
        .context("start_workflow(child)")?;
    eprintln!("JAR2-81 happy: child started at {child_workflow_id}");

    // Wait for the child to retire — its scripted sequence terminates
    // after `EmitOutput → Retire`. The `Decision::EmitOutput` arm fires
    // the ChildOutput signal at the parent before the next tick's Retire.
    let child_result: AgentResult = child_handle
        .get_result(WorkflowGetResultOptions::default())
        .await
        .context("child get_result")?;
    let AgentResult::Retired { reason } = child_result;
    assert!(
        reason.contains("scripted retire"),
        "child workflow returned wrong retire reason: {reason:?}"
    );
    eprintln!("JAR2-81 happy: child retired cleanly");

    // Poll the parent's `inspect_state` until cumulative_triggers_observed >= 1.
    // The signal command is recorded on the child's history when its
    // workflow task completes; the parent's signal-handler fires on its
    // next workflow task. On a healthy server this lands within
    // milliseconds of the child's retirement, but we budget generously.
    let poll_start = std::time::Instant::now();
    let poll_budget = Duration::from_secs(30);
    let mut observed_at_parent: Option<AgentSnapshot> = None;
    let mut last_err: Option<anyhow::Error> = None;
    while poll_start.elapsed() < poll_budget {
        match parent_handle
            .execute_update(
                AgentWorkflow::inspect_state,
                (),
                WorkflowExecuteUpdateOptions::default(),
            )
            .await
        {
            Ok(snap) => {
                if snap.cumulative_triggers_observed >= 1 {
                    observed_at_parent = Some(snap);
                    break;
                }
            }
            Err(e) => {
                last_err = Some(anyhow::anyhow!("inspect_state error: {e}"));
            }
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
    }
    let observed_at_parent = observed_at_parent.ok_or_else(|| {
        last_err.unwrap_or_else(|| {
            anyhow::anyhow!(
                "parent's cumulative_triggers_observed stayed at 0 across 30s poll budget"
            )
        })
    })?;
    eprintln!(
        "JAR2-81 happy: parent observed cumulative_triggers_observed={}",
        observed_at_parent.cumulative_triggers_observed
    );
    assert!(
        observed_at_parent.cumulative_triggers_observed >= 1,
        "parent did not observe the ChildOutput signal: {observed_at_parent:?}"
    );

    // Now retire the parent so the worker can drain. The parent's
    // `RoutingDecide` will see the queued trigger on the next tick (or
    // already saw it via the wake gate); either way the retire signal
    // short-circuits the tick before any further decision.
    parent_handle
        .signal(
            AgentWorkflow::retire,
            "JAR2-81 happy: test asked".to_string(),
            WorkflowSignalOptions::default(),
        )
        .await
        .context("signal parent retire")?;
    let parent_result: AgentResult = parent_handle
        .get_result(WorkflowGetResultOptions::default())
        .await
        .context("parent get_result")?;
    let AgentResult::Retired {
        reason: parent_reason,
    } = parent_result;
    assert!(
        parent_reason.contains("test asked"),
        "parent returned wrong retire reason: {parent_reason:?}"
    );

    // Inspect the trigger payload the parent's `RoutingDecide` recorded.
    // The parent may observe the trigger across one or more tick
    // bundles; assert at least one ChildOutput is in the captured set.
    let observed = parent_observed_triggers_snapshot();
    eprintln!(
        "JAR2-81 happy: parent's RoutingDecide saw {} trigger(s)",
        observed.len()
    );
    let child_outputs: Vec<&Trigger> = observed
        .iter()
        .filter(|t| matches!(t, Trigger::ChildOutput { .. }))
        .collect();
    assert!(
        !child_outputs.is_empty(),
        "parent's RoutingDecide never saw a ChildOutput trigger; captured: {observed:?}"
    );
    let Trigger::ChildOutput {
        child_ref,
        agent_name,
        output_id,
    } = child_outputs[0]
    else {
        unreachable!("filter above guarantees ChildOutput");
    };
    assert_eq!(
        child_ref.workflow_id, child_workflow_id,
        "ChildOutput.child_ref.workflow_id mismatch"
    );
    assert_eq!(
        child_ref.agent_id, child_agent_id,
        "ChildOutput.child_ref.agent_id mismatch"
    );
    assert_eq!(agent_name, "fda_scraper", "ChildOutput.agent_name mismatch");
    // The OutputId is the content-addressed hash of the child's
    // (content, evidence). The child wrote ("JAR2-81 child output",
    // [planted_id]); compare the trigger's OutputId against what the
    // child's `persist_output` activity should have minted by
    // round-tripping the same shape through `AgentFs::persist_output`'s
    // on-disk index. Cheaper: look up the child's outputs/_tail.json
    // and assert the trigger's id matches.
    let inspect_mandate = Mandate::new("inspect", Duration::from_millis(0), None);
    let inspect_storage: Arc<dyn AgentStorage> = SHARED_STORAGE
        .get()
        .expect("SHARED_STORAGE installed")
        .clone();
    let inspect_fs = AgentFs::new_with_storage(inspect_storage, child_prefix, &inspect_mandate)
        .await
        .context("open inspecting AgentFs over child")?;
    let outs = inspect_fs
        .list_recent_outputs(8)
        .await
        .context("list_recent_outputs on child")?;
    assert_eq!(
        outs.len(),
        1,
        "expected exactly one output on the child's FS; got {}",
        outs.len()
    );
    assert_eq!(
        &outs[0].id, output_id,
        "Trigger::ChildOutput.output_id must match the child's persisted output id"
    );

    // Sanity: the child's output cites the planted evidence (proves
    // `persist_output` ran end-to-end against the real activity body,
    // not a stub).
    assert!(
        outs[0].evidence.contains(&planted_id),
        "child's persisted output must cite the planted evidence id"
    );

    let _ = parent_prefix; // retained for symmetry / future use

    Ok(())
}

async fn run_failure_path() -> Result<()> {
    let suffix = run_suffix();
    let task_queue = format!("jarvis-jar2-81-fail-{suffix}");
    let child_prefix = format!("graphs/g-jar2-81-fail/agents/child-{suffix}");
    let child_workflow_id = format!("graphs/g-jar2-81-fail/agents/child-{suffix}");
    // Deliberately unused workflow id — no `start_workflow` ever runs
    // against this id.
    let missing_parent_workflow_id =
        format!("graphs/g-jar2-81-fail/agents/parent-DOES-NOT-EXIST-{suffix}");

    let storage = ensure_installed();
    reset_parent_observed_triggers();

    let plant_mandate = Mandate::new("plant", Duration::from_millis(0), None);
    let plant_storage: Arc<dyn AgentStorage> = storage.clone();
    let plant_fs = AgentFs::new_with_storage(plant_storage, &child_prefix, &plant_mandate)
        .await
        .context("open planting AgentFs for child (failure path)")?;
    let planted_id = plant_fs
        .record_evidence(EvidenceRecord::new(
            "echo",
            serde_json::json!({"k": "vv"}),
            serde_json::json!({"hit": true}),
            Utc::now(),
        ))
        .await
        .context("plant evidence for child EmitOutput (failure path)")?;

    let child_script = vec![
        Decision::EmitOutput {
            content: "JAR2-81 child (failure path) output".into(),
            evidence: vec![planted_id.clone()],
        },
        Decision::Retire {
            reason: "JAR2-81 failure path: scripted retire".into(),
        },
    ];
    install_role_scripts(Vec::new(), child_script);

    let telemetry_options = TelemetryOptions::builder().build();
    let runtime = CoreRuntime::new_assume_tokio(
        RuntimeOptions::builder()
            .telemetry_options(telemetry_options)
            .build()
            .map_err(|e| anyhow::anyhow!("RuntimeOptions build failed: {e}"))?,
    )?;
    let client = build_client().await?;
    let mut worker = build_worker(&runtime, client.clone(), &task_queue)?;
    let shutdown = worker.shutdown_handle();

    let driver_task_queue = task_queue.clone();
    let driver_child_prefix = child_prefix.clone();
    let driver_child_workflow_id = child_workflow_id.clone();
    let driver_missing_parent_workflow_id = missing_parent_workflow_id.clone();
    let driver = tokio::spawn(async move {
        struct ShutdownGuard<F: Fn()>(F);
        impl<F: Fn()> Drop for ShutdownGuard<F> {
            fn drop(&mut self) {
                (self.0)();
            }
        }
        let _guard = ShutdownGuard(shutdown);
        drive_failure_path(
            client,
            &driver_task_queue,
            &driver_child_workflow_id,
            &driver_child_prefix,
            &driver_missing_parent_workflow_id,
        )
        .await
    });

    let worker_result = tokio::time::timeout(Duration::from_secs(60), worker.run())
        .await
        .map_err(|_| anyhow::anyhow!("worker.run() timed out (60s)"))?
        .map_err(|e| anyhow::anyhow!("worker.run() exited with error: {e}"));
    let driver_result = driver.await.context("driver task panicked")?;

    worker_result?;
    driver_result?;
    Ok(())
}

async fn drive_failure_path(
    client: Client,
    task_queue: &str,
    child_workflow_id: &str,
    child_prefix: &str,
    missing_parent_workflow_id: &str,
) -> Result<()> {
    let child_agent_uuid =
        Uuid::parse_str("66666666-7777-8888-9999-aaaaaaaaaaaa").expect("hand-picked uuid is valid");
    let child_input = AgentInput {
        cfg: Default::default(),
        fs_handle: FsHandle {
            prefix: child_prefix.into(),
        },
        parent_handle: Some(ParentRef {
            workflow_id: missing_parent_workflow_id.to_string(),
            ..ParentRef::default()
        }),
        carryover: None,
        mandate: Mandate::new(CHILD_MANDATE_TEXT, Duration::from_millis(50), None),
        graph_id: GraphId::new(Uuid::nil()),
        agent_id: AgentId::new(child_agent_uuid),
        agent_name: "orphan_child".into(),
    };
    let child_handle = client
        .start_workflow(
            AgentWorkflow::run,
            child_input,
            WorkflowStartOptions::new(task_queue, child_workflow_id).build(),
        )
        .await
        .context("start_workflow(child failure path)")?;
    eprintln!(
        "JAR2-81 fail: child started at {child_workflow_id}, parent_handle points at \
         non-existent {missing_parent_workflow_id}"
    );

    // The load-bearing assertion: despite the signal target being a
    // non-existent workflow, the child's workflow body does NOT error
    // out — it logs the failure and continues to the next tick
    // (Retire). Stage 5 Project decision 10.
    let result: AgentResult = child_handle
        .get_result(WorkflowGetResultOptions::default())
        .await
        .context("child get_result (failure path)")?;
    let AgentResult::Retired { reason } = result;
    assert!(
        reason.contains("scripted retire"),
        "child workflow did not complete normally despite signal-to-nonexistent-parent failure; \
         got: {reason:?}"
    );
    eprintln!("JAR2-81 fail: child completed normally after signal failure (Stage 5 decision 10)");

    // Sanity: the child's output still landed on its own FS — losing
    // the signal does not lose the data.
    let inspect_mandate = Mandate::new("inspect", Duration::from_millis(0), None);
    let inspect_storage: Arc<dyn AgentStorage> = SHARED_STORAGE
        .get()
        .expect("SHARED_STORAGE installed")
        .clone();
    let inspect_fs = AgentFs::new_with_storage(inspect_storage, child_prefix, &inspect_mandate)
        .await
        .context("open inspecting AgentFs over child (failure path)")?;
    let outs = inspect_fs
        .list_recent_outputs(8)
        .await
        .context("list_recent_outputs on child (failure path)")?;
    assert_eq!(
        outs.len(),
        1,
        "expected child to have persisted its output despite parent-unreachable; got {}",
        outs.len()
    );

    Ok(())
}
